# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisdata', '0002_auto_20160813_1708'),
        ('regspecies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regplantae',
            name='data2',
        ),
        migrations.AddField(
            model_name='regplantae',
            name='patch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisdata.gisArea'),
        ),
    ]
