# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regspecies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regplantae',
            name='data1',
        ),
        migrations.AddField(
            model_name='regplantae',
            name='ptype',
            field=models.CharField(choices=[('SB', 'Seed Bearing'), ('IG', 'Ingeneous tree'), ('IP', 'Indegenous patch')], max_length=2, null=True),
        ),
    ]
