# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regspecies', '0002_auto_20160813_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regplantae',
            name='islive',
        ),
    ]
