# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaeImages',
            fields=[
                ('images', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='images/')),
                ('image1', models.ImageField(null=True, upload_to='images/')),
                ('image2', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
