# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gisdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('best', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('beatname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('division_name', models.CharField(max_length=40)),
                ('gisArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisdata.gisArea')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('ranges', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('rangename', models.CharField(max_length=30)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Division')),
                ('gisArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisdata.gisArea')),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Division'),
        ),
        migrations.AddField(
            model_name='beat',
            name='gisArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisdata.gisArea'),
        ),
        migrations.AddField(
            model_name='beat',
            name='ranges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Range'),
        ),
    ]
