# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='beat',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
