# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='division',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='range',
            name='is_active',
        ),
    ]
