# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginInfo',
        ),
    ]
