# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantae',
            fields=[
                ('plantae', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=40)),
                ('local_name', models.CharField(max_length=40)),
                ('apd', models.CharField(choices=[('invt', 'anti-invertebrate defenses'), ('vert', 'anti-vertebrate defenses'), ('v/it', 'both kinds of defenses'), ('none', 'no defence')], max_length=4)),
                ('canopy_height', models.PositiveSmallIntegerField()),
                ('Phylum', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('Series', models.CharField(max_length=30)),
                ('Family', models.CharField(max_length=30)),
                ('Genus', models.CharField(max_length=30)),
                ('Species', models.CharField(max_length=30)),
                ('distribution', models.CharField(choices=[('CL', 'clumped'), ('DI', 'dispersed')], max_length=2)),
                ('evapotranspiration', models.CharField(choices=[('DM', 'dimorph_meso-hygro'), ('DX', 'dimorph_xero-meso'), ('HY', 'hygromorphic'), ('ME', 'mesomorphic'), ('XE', 'xeromorphic')], max_length=2)),
                ('leaf_dissection', models.CharField(choices=[('PA', 'palmately_cmpd'), ('PI', 'pinnately_cmpd'), ('PT', 'pinnatifid'), ('SI', 'simple'), ('SP', 'simple_palmate'), ('SE', 'simple_pinnate')], max_length=2)),
                ('leaf_margin', models.CharField(choices=[('DT', 'drip_tip'), ('ET', 'entire'), ('LB', 'lobed'), ('LT', 'lobed+th'), ('TO', 'toothed')], max_length=2)),
                ('leaf_size', models.CharField(choices=[('MA', 'macrophyll'), ('ME', 'megaphyll'), ('MS', 'mesophyll'), ('MI', 'microphyll'), ('NA', 'nanophyll'), ('NO', 'notophyll')], max_length=2)),
                ('life_form', models.CharField(choices=[('01', 'cespitose'), ('02', 'decumbent'), ('03', 'emerg_aquat'), ('04', 'epiphyte'), ('05', 'float_aqu'), ('06', 'ground_cover'), ('07', 'herb'), ('08', 'herb_liana'), ('09', 'parasite'), ('10', 'perenn_herb'), ('11', 'procumbent'), ('12', 'prostrate'), ('13', 'semi_self_su'), ('14', 'shrub'), ('15', 'small_tree'), ('16', 'tree'), ('17', 'woody_liana')], max_length=2)),
                ('lifespan', models.CharField(choices=[('AN', 'annual'), ('LP', 'long_liv_perennial'), ('MC', 'monocarpic'), ('SL', 'short_liv_perennia')], max_length=2)),
                ('main_axis_diameter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('phenology', models.CharField(choices=[('DE', 'deciduous'), ('EV', 'evergreen')], max_length=2)),
                ('pollen_aggregation', models.CharField(choices=[('MO', 'monad'), ('OT', 'other')], max_length=2)),
                ('pollen_size', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pollen_surface', models.CharField(choices=[('SC', 'sculptured'), ('SM', 'smooth')], max_length=2)),
                ('pollen_vector', models.CharField(choices=[('AN', 'animal'), ('WA', 'water'), ('WN', 'wind')], max_length=2)),
                ('seed_dispersal', models.CharField(choices=[('EA', 'endo-animal'), ('EX', 'exo-animal'), ('NO', 'none'), ('WA', 'water'), ('WI', 'wind')], max_length=2)),
                ('seeds_diaspore', models.PositiveSmallIntegerField()),
                ('seed_size_class', models.PositiveSmallIntegerField()),
                ('sporophyte_cost', models.CharField(choices=[('KP', 'K+'), ('KM', 'K-'), ('RP', 'r+'), ('RM', 'r-'), ('RK', 'r-K'), ('UN', 'unknown')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PlantaeAssamese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=40)),
                ('local_name', models.CharField(max_length=40)),
                ('comments', models.TextField(max_length=300)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciesdata.Plantae')),
            ],
        ),
        migrations.CreateModel(
            name='PlantaeBengali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=40)),
                ('local_name', models.CharField(max_length=40)),
                ('comments', models.TextField(max_length=300)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciesdata.Plantae')),
            ],
        ),
        migrations.CreateModel(
            name='PlantaeHindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=40)),
                ('local_name', models.CharField(max_length=40)),
                ('comments', models.TextField(max_length=300)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciesdata.Plantae')),
            ],
        ),
    ]
