# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciesdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantae',
            name='status',
        ),
    ]
