# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciesdata', '0002_auto_20160802_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantae',
            name='status',
            field=models.BinaryField(default=True),
        ),
    ]
