# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gisArea',
            fields=[
                ('gisarea', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('areaType', models.CharField(choices=[('BT', 'Beat'), ('RN', 'Range'), ('DI', 'Division'), ('IG', 'Indegenous Patch')], max_length=2, null=True)),
                ('boundry', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
        ),
    ]
