# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 17:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cordinates',
            name='area',
        ),
        migrations.AddField(
            model_name='gisarea',
            name='areaType',
            field=models.CharField(choices=[('BT', 'Beat'), ('RN', 'Range'), ('DI', 'Division')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gisarea',
            name='boundry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='cordinates',
        ),
    ]
