# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisdata', '0002_auto_20160813_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisarea',
            name='areaType',
            field=models.CharField(choices=[('BT', 'Beat'), ('RN', 'Range'), ('DI', 'Division'), ('IG', 'Indegenous Patch')], max_length=2, null=True),
        ),
    ]
