# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDeposit',
            fields=[
                ('resourcebank', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('body_type', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('body_id', models.PositiveIntegerField()),
                ('resource_type', models.CharField(choices=[('SD', 'Seed')], max_length=2)),
                ('resource_bank_id', models.PositiveIntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('open_date', models.DateField(auto_now_add=True)),
                ('open_time', models.TimeField(auto_now_add=True)),
                ('last_updated_date', models.DateField(auto_now=True)),
                ('last_updated_time', models.TimeField(auto_now=True)),
                ('status', models.BinaryField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedDeposit',
            fields=[
                ('bank', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('body_type', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('body_id', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('open_date', models.DateField(auto_now_add=True)),
                ('open_time', models.TimeField(auto_now_add=True)),
                ('last_updated_date', models.DateField(auto_now=True)),
                ('last_updated_time', models.TimeField(auto_now=True)),
                ('status', models.BinaryField(default=True)),
            ],
        ),
    ]
