# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcedeposit',
            name='district',
        ),
        migrations.RemoveField(
            model_name='resourcedeposit',
            name='state',
        ),
        migrations.RemoveField(
            model_name='seeddeposit',
            name='district',
        ),
        migrations.RemoveField(
            model_name='seeddeposit',
            name='state',
        ),
        migrations.AlterField(
            model_name='resourcedeposit',
            name='source_species',
            field=models.PositiveIntegerField(),
        ),
    ]
