# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciesdata', '0001_initial'),
        ('resourcebank', '0002_remove_seeddeposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedeposit',
            name='source_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speciesdata.Plantae'),
        ),
        migrations.AddField(
            model_name='seeddeposit',
            name='source_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speciesdata.Plantae'),
        ),
    ]
