# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resourcebank', '0001_initial'),
        ('regspecies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedCollection',
            fields=[
                ('seedcollection', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('collfromg', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('colltog', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('collfromg_id', models.PositiveIntegerField()),
                ('colltog_id', models.PositiveIntegerField()),
                ('collfromU', models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer')], max_length=2)),
                ('colltoU', models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer')], max_length=2)),
                ('collfromU_id', models.PositiveIntegerField()),
                ('colltoU_id', models.PositiveIntegerField()),
                ('coll_amount', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regspecies.RegPlantae')),
            ],
        ),
        migrations.CreateModel(
            name='SeedDistribution',
            fields=[
                ('seeddistribution', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('disfromg', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('distog', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('disfromg_id', models.PositiveIntegerField()),
                ('distog_id', models.PositiveIntegerField()),
                ('disfromU', models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer')], max_length=2)),
                ('distoU', models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer')], max_length=2)),
                ('disfromU_id', models.PositiveIntegerField()),
                ('distoU_id', models.PositiveIntegerField()),
                ('dis_amount', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regspecies.RegPlantae')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('trantype', models.CharField(choices=[('CO', 'Collection'), ('DS', 'Distribution')], max_length=2)),
                ('tran_id', models.PositiveIntegerField()),
                ('trangood', models.CharField(choices=[('SD', 'Seed')], max_length=2)),
                ('regbeing_type', models.CharField(choices=[('PL', 'Plant')], max_length=2)),
                ('regbeing_id', models.PositiveIntegerField()),
                ('tranfromg', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('trantog', models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat')], max_length=2)),
                ('tranfromg_id', models.PositiveIntegerField()),
                ('trantog_id', models.PositiveIntegerField()),
                ('tranfromU', models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer')], max_length=2)),
                ('trantoU', models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer')], max_length=2)),
                ('tranfromU_id', models.PositiveIntegerField()),
                ('trantoU_id', models.PositiveIntegerField()),
                ('transaction_amount', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bal_add_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='resourcebank.ResourceDeposit')),
                ('bal_dec_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='resourcebank.ResourceDeposit')),
            ],
        ),
    ]
