# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcetransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedcollection',
            name='collfromU',
            field=models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer'), ('RS', 'RegSpecies')], default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='collfromU_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='collfromg',
            field=models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat'), ('BC', 'Beat_collection')], default='BC', max_length=2),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='collfromg_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='colltoU',
            field=models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer'), ('CC', 'Government_customer')], default='BO', max_length=2),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='colltog',
            field=models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat'), ('DD', 'Division_distribution')], default='BT', max_length=2),
        ),
        migrations.AlterField(
            model_name='seeddistribution',
            name='disfromU',
            field=models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer'), ('RS', 'RegSpecies')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seeddistribution',
            name='disfromg',
            field=models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat'), ('BC', 'Beat_collection')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seeddistribution',
            name='distoU',
            field=models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer'), ('CC', 'Government_customer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seeddistribution',
            name='distog',
            field=models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat'), ('DD', 'Division_distribution')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tranfromU',
            field=models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer'), ('RS', 'RegSpecies')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tranfromg',
            field=models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat'), ('BC', 'Beat_collection')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trantoU',
            field=models.CharField(choices=[('DO', 'Division officer'), ('RO', 'Range officer'), ('BO', 'Beat officer'), ('CC', 'Government_customer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trantog',
            field=models.CharField(choices=[('DI', 'Division'), ('RN', 'Range'), ('BT', 'Beat'), ('DD', 'Division_distribution')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trantype',
            field=models.CharField(choices=[('CO', 'Collection'), ('DS', 'Distribution'), ('SC', 'Species_Collection'), ('GC', 'Distributed_body')], max_length=2),
        ),
    ]
